"""
eSewa Merchant Credential Validator

This script helps verify if your eSewa credentials are correct.
Run this to test different scenarios.
"""

import hmac
import hashlib
import base64
from decimal import Decimal

def generate_signature(key, message):
    """Generate HMAC-SHA256 signature"""
    key = key.encode('utf-8')
    message = message.encode('utf-8')
    hmac_sha256 = hmac.new(key, message, hashlib.sha256)
    digest = hmac_sha256.digest()
    signature = base64.b64encode(digest).decode('utf-8')
    return signature

print("""
╔════════════════════════════════════════════════════════════════╗
║     eSewa Credential Verification Tool                       ║
║                                                                ║
║  Run this script to test if your merchant credentials work    ║
╚════════════════════════════════════════════════════════════════╝

INSTRUCTIONS:
1. Get the ACTUAL secret key from your eSewa merchant dashboard
2. Update the secret_key variable below
3. Run this script
4. Compare the generated signature with what you expect

IMPORTANT:
- The default '8gBm/:&EnhH.1/q' is eSewa's PUBLIC test credential
- It may not work with all test accounts
- Your merchant account should have its OWN secret key
""")

# ============================================================================
# CONFIGURATION - Update these with YOUR credentials
# ============================================================================

SECRET_KEY = '8gBm/:&EnhH.1/q'  # ← Update this with YOUR secret key from eSewa
MERCHANT_CODE = 'EPAYTEST'
PRODUCT_CODE = 'EPAYTEST'

# Test transaction data
TEST_AMOUNT = '100.00'
TEST_UUID = 'test-uuid-12345-67890'
TEST_PRODUCT = 'EPAYTEST'

# ============================================================================
# TESTS
# ============================================================================

print("\n" + "="*70)
print("TEST 1: Signature Generation with YOUR Secret Key")
print("="*70)

data_to_sign = f"total_amount={TEST_AMOUNT},transaction_uuid={TEST_UUID},product_code={TEST_PRODUCT}"
your_signature = generate_signature(SECRET_KEY, data_to_sign)

print(f"\nYour Secret Key: {SECRET_KEY[:10]}...{SECRET_KEY[-10:]}")
print(f"Merchant Code: {MERCHANT_CODE}")
print(f"Product Code: {PRODUCT_CODE}")
print(f"\nTest Data:")
print(f"  Amount: {TEST_AMOUNT}")
print(f"  Transaction UUID: {TEST_UUID}")
print(f"  Product Code: {TEST_PRODUCT}")
print(f"\nGenerated Signature: {your_signature}")

# ============================================================================
# Test different amount formats
print("\n" + "="*70)
print("TEST 2: Different Amount Formats")
print("="*70)

amount_formats = {
    'With decimals (100.00)': '100.00',
    'Without decimals (100)': '100',
    'In paisa (10000)': '10000',
}

for format_name, amount in amount_formats.items():
    data = f"total_amount={amount},transaction_uuid={TEST_UUID},product_code={TEST_PRODUCT}"
    sig = generate_signature(SECRET_KEY, data)
    print(f"\n{format_name}:")
    print(f"  Data: {data}")
    print(f"  Signature: {sig}")

# ============================================================================
# Test with default eSewa test key for comparison
print("\n" + "="*70)
print("TEST 3: Comparison with Default eSewa Test Key")
print("="*70)

DEFAULT_KEY = '8gBm/:&EnhH.1/q'
data = f"total_amount={TEST_AMOUNT},transaction_uuid={TEST_UUID},product_code={TEST_PRODUCT}"
default_sig = generate_signature(DEFAULT_KEY, data)

print(f"\nUsing eSewa Default Test Key: {DEFAULT_KEY[:10]}...{DEFAULT_KEY[-10:]}")
print(f"Generated Signature: {default_sig}")
print(f"\nYour Secret Key Signature: {your_signature}")
print(f"Signatures Match: {your_signature == default_sig}")

if your_signature != default_sig:
    print("\n⚠️  Your secret key is DIFFERENT from the default test key")
    print("   This is CORRECT if your merchant account uses a custom key")
    print("   This is WRONG if your merchant account should use the default key")

# ============================================================================
# Practical next steps
print("\n" + "="*70)
print("WHAT TO DO NEXT")
print("="*70)

print("""
1. IF YOU SEE A SIGNATURE ABOVE:
   ✓ Your secret key is being processed correctly
   ✓ The algorithm is working
   
2. IF STILL GETTING ES104 ERROR:
   ✓ Probably need a different secret key
   ✓ Contact eSewa and ask for your merchant secret key
   ✓ Make sure you're using the correct key for TEST environment
   
3. TO TEST YOUR ACTUAL INTEGRATION:
   ✓ Use the amount/UUID from your order
   ✓ Compare with signature generated by Django
   ✓ They should match exactly
   
4. IF SIGNATURES DON'T MATCH:
   ✗ Check for whitespace differences
   ✗ Check for character encoding issues
   ✗ Verify amount format matches
   ✗ Verify field order: total_amount, transaction_uuid, product_code
""")

# ============================================================================
# Interactive testing
print("\n" + "="*70)
print("VERIFY YOUR CURRENT SETUP")
print("="*70)

try:
    # Try to load from environment
    import os
    from dotenv import load_dotenv
    
    load_dotenv()
    
    env_key = os.getenv('ESEWA_SECRET_KEY')
    env_merchant = os.getenv('ESEWA_MERCHANT_CODE')
    env_product = os.getenv('ESEWA_PRODUCT_CODE')
    
    print("\nLoaded from .env file:")
    print(f"  ESEWA_SECRET_KEY: {env_key[:10] if env_key else 'NOT SET'}...")
    print(f"  ESEWA_MERCHANT_CODE: {env_merchant}")
    print(f"  ESEWA_PRODUCT_CODE: {env_product}")
    
    if env_key:
        print("\n✓ Environment variables are configured in .env")
    else:
        print("\n✗ Environment variables not found in .env")
        
except ImportError:
    print("\nNote: python-dotenv not installed, skipping .env check")

print("\n" + "="*70)
print("END OF VERIFICATION")
print("="*70)
